version: "2.2"

services:
  cube:
    image: cubejs/cube:latest
    ports:
      # Cube.js API and Developer Playground
      - ${PORT}:4000
      # Dashboard app, if created
      - ${APP_DASHBOARD_PORT}:3000
    env_file:
      - .env
    volumes:
      - .:/cube/conf
